// This file was automatically generated by the AI assistant.

export type User = {
  id: number;
  name: string;
  email: string;
};

export type Product = {
  id: number;
  name: string;
  price: number;
  description: string;
};

export type CartItem = {
  product: Product;
  quantity: number;
};

export type Cart = {
  items: CartItem[];
};

export interface Territory {
  name: string
  id: number
  x: number
  y: number
  width: number
  height: number
  ownerId: number
  resourceGeneration: { money: number; supplies: number; manpower: number }
  terrain: string

  handleBattleResult(attackSuccessful: boolean, attackerId: number): void
}

export class DefaultTerritory implements Territory {
  constructor(
    public name: string,
    public id: number,
    public x: number,
    public y: number,
    public width: number,
    public height: number,
    public ownerId: number,
    public resourceGeneration: { money: number; supplies: number; manpower: number },
    public terrain: string
  ) {}

  handleBattleResult(attackSuccessful: boolean, attackerId: number): void {
    if (attackSuccessful) this.ownerId = attackerId
  }
}

export type UnitType = 'worker' | 'building' | 'resource' | 'Infantry';

export type Unit = {
  id: number;
  name: string;
  type: UnitType;
  x: number;
  y: number;
  selected: boolean;
  territoryId: number;
  ownerId: number;
  count: number;
};